{{- if .Values.managedServiceAccount }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Chart.Name }}-cluster-role
  labels:
    {{- include "oomkill-monitor.labels" . | nindent 4 }}
rules: {{ toYaml .Values.clusterRoleRules | nindent 2 -}}
{{- end -}}
