apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    {{- include "oomkiller-monitor.labels" . | nindent 4 }}
  name: {{ .Chart.Name }}
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "oomkiller-monitor.selectorLabels" . | nindent 4 }}
  template:
    metadata:
      labels:
        {{- include "oomkiller-monitor.labels" . | nindent 4 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - env:
        - name: DOCKER
          value: "true"
        - name: CONTAINERD
          value: "false"
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        name: {{ .Chart.Name }}
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources: {}
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: dockersock
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      volumes:
      - hostPath:
          path: /var/run/docker.sock
          type: ""
        name: dockersock
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate

