apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/instance: missing-container-metrics
    app.kubernetes.io/name: missing-container-metrics
  name: missing-container-metrics
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: missing-container-metrics
      app.kubernetes.io/name: missing-container-metrics
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: missing-container-metrics
        app.kubernetes.io/name: missing-container-metrics
    spec:
      affinity: {}
      containers:
      - env:
        - name: DOCKER
          value: "true"
        - name: CONTAINERD
          value: "false"
        image: dmilhdef/missing-container-metrics:v0.21.0
        imagePullPolicy: IfNotPresent
        name: missing-container-metrics
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources: {}
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: dockersock
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoExecute
        operator: Exists
      - effect: NoSchedule
        operator: Exists
      volumes:
      - hostPath:
          path: /var/run/docker.sock
          type: ""
        name: dockersock
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate

