# secret for yandex-cloud container registry
---
apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.global.yc_secret }}
kind: Secret
metadata:
  name: sirius-registry
  labels:
    app: {{ template "oomkill-monitor.name" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: kubernetes.io/dockerconfigjson

# secret for sirius-gitlab container registry
---
apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.global.gitlab_secret }}
kind: Secret
metadata:
  name: gitlab-registry
  labels:
    app: {{ template "oomkill-monitor.name" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: kubernetes.io/dockerconfigjson

