apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.global.secret }}
kind: Secret
metadata:
  name: sirius-registry
  labels:
    app: {{ template "oomkiller-monitor.name" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: kubernetes.io/dockerconfigjson

