apiVersion: v1
kind: Service
metadata:
  labels:
    app: missing-container-metrics
  name: missing-container-metrics
spec:
  ports:
  - name: metrics
    port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app.kubernetes.io/name: missing-container-metrics
  sessionAffinity: None
  type: ClusterIP

