stages:
  - package-publish

helm-package-publish:
  when: manual
  stage: package-publish
  image:
    name: registry.sirius.online/infra/images/helm:3.12.3
    entrypoint: [""]
  tags:
    - corp-docker
  variables:
    REPO: oomkill-monitor
    CHART: oomkill-monitor
  before_script:
    - set -x
    - apk update && apk add git --no-cache
    - helm plugin install https://github.com/chartmuseum/helm-push
    - >
      helm repo add oomkill-monitor
      --username ${CI_REGISTRY_USER}
      --password ${CI_REGISTRY_PASSWORD}
      ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/stable
  script:
    - helm package charts/oomkill-monitor
    - helm cm-push oomkill-monitor*.tgz oomkill-monitor
    - helm search oomkill-monitor
#  only:
#    refs:
#      - main
#    changes:
#      - chart/**/*