stages:
  - sirius

.base-oomkill-monitor:
  when: manual
  before_script:
    - echo 'Deploy parameters:'
    - echo 'CLUSTER_NAME =>' ${CLUSTER_NAME}
  script:
    - chmod +x ./scripts/helm_deploy_and_wait.sh
    - RELEASE_NAME="oomkill-monitor"
      NAMESPACE="oomkill-monitor"
      CHART="chart"
      HELM_ARGS="
      -f chart/conf/${CLUSTER_NAME}/values.yaml
      --set global.yc_secret="${YC_REGISTRY}"
      --set global.gitlab_secret="${INFRA_REGISTRY}"
      --debug"
      ./scripts/helm_deploy_and_wait.sh

############  SIRIUS  ############

sirius oomkill-monitor prod:
  extends:
    - .base-oomkill-monitor
  stage: sirius
  variables:
    CLUSTER_NAME: "sirius"
  tags:
    - kube-ci