stages:
  - package-publish

helm-package-publish:
  when: manual
  stage: package-publish
  image:
    name: registry.sirius.online/infra/images/helm:3.12.3
    entrypoint: [""]
  tags:
    - corp-docker
  variables:
    REPO: oomkill-monitor
    CHART: oomkill-monitor
  before_script:
    - set -x
    - apk update && apk add git curl --no-cache
#    - helm plugin install https://github.com/chartmuseum/helm-push
    - >
      helm repo add oomkill-monitor
      --username ${CI_REGISTRY_USER}
      --password ${CI_REGISTRY_PASSWORD}
      ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/stable
  script:
    - helm package charts/oomkill-monitor
    - ls -la
    - >
      curl --request POST
      --form 'chart=@oomkill-monitor-1.0.0.tgz'
      --user zerodistance:glpat-dxTFQxAzC1PJV-3Ec62y
      https://gitlab.sirius.online/api/v4/projects/105/packages/helm/api/stable/charts
#    - helm cm-push oomkill-monitor*.tgz oomkill-monitor
    - helm search repo oomkill-monitor
#  only:
#    refs:
#      - main
#    changes:
#      - chart/**/*