stages:
  - cpm
  - corp
  - univ
  - sirius

.base-oomkill-monitor:
  when: manual
  before_script:
    - echo 'Deploy parameters:'
    - echo 'CLUSTER_NAME =>' ${CLUSTER_NAME}
  script:
    - kubectl get ns oomkill-monitor || kubectl create ns oomkill-monitor
    - chmod +x ./scripts/helm_deploy_and_wait.sh
    - RELEASE_NAME="oomkill-monitor"
      NAMESPACE="oomkill-monitor"
      CHART="chart"
      HELM_ARGS="
      -f deploy/helm/conf/${CLUSTER_NAME}/values.yaml
      --set global.yc_secret="${YC_REGISTRY}"
      --set global.gitlab_secret="${INFRA_REGISTRY}"
      --atomic
      --wait"
      ./scripts/helm_deploy_and_wait.sh

############  CPM-DEV  ############

cpm oomkill-monitor stage:
  extends:
    - .base-oomkill-monitor
  stage: cpm
  variables:
    CLUSTER_NAME: "cpm-dev"
  tags:
    - kube-cpm

############  CPM-YC  ############

cpm oomkill-monitor prod:
  extends:
    - .base-oomkill-monitor
  stage: cpm
  variables:
    CLUSTER_NAME: "cpm"
  tags:
    - cpm-yac

############  CORP  ############

corp oomkill-monitor prod:
  extends:
    - .base-oomkill-monitor
  stage: corp
  variables:
    CLUSTER_NAME: "corp"
  tags:
    - kube-corp

############  UNIV  ############

univ oomkill-monitor prod:
  extends:
    - .base-oomkill-monitor
  stage: univ
  variables:
    CLUSTER_NAME: "univ"
  tags:
    - kube-univ

############  SIRIUS  ############

sirius oomkill-monitor prod:
  extends:
    - .base-oomkill-monitor
  stage: sirius
  variables:
    CLUSTER_NAME: "sirius"
  tags:
    - kube-ci