{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "oomkill-monitor.selectorLabels" . | nindent 4 }}
    release: {{ .Values.serviceMonitor.release }}
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
  - honorLabels: true
    interval: 30s
    metricRelabelings:
    - action: keep
      regex: container_ooms
      sourceLabels:
      - __name__
    - action: labeldrop
      regex: (container|container_id|container_short_id|docker_container_id|image_id)
    path: /metrics
    targetPort: {{ .Values.service.port }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
{{- end -}}