apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "oomkill-monitor.labels" . | nindent 4 }}
  name: {{ .Chart.Name }}
spec:
  ports:
  - name: metrics
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  selector:
    {{- include "oomkill-monitor.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: {{ .Values.service.type }}

