### Настройки для кластера SIRIUS

# Инициация создания RBAC конфигураций
managedServiceAccount: true

# Правила для ClusterRole-манифеста
clusterRoleRules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - nodes
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "apps"
    resources:
      - replicasets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resourceNames:
      - oomkill-monitor-psp
    resources:
      - podsecuritypolicies
    verbs:
      - use
