apiVersion: v1
description: Exposes metrics about Docker/Containerd containers. Each of those metrics, are published with the labels.
name: missing-container-metrics
version: 1.0.0
appVersion: v0.21.0

